name: 'Frodo CLI Release Pipeline'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version'
    runs-on: ubuntu-latest

    steps:
      - name: Bump version
        id: version-bump
        uses: remorses/bump-version@js
        with:
          version_file: ./VERSION
          prefix: v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Output Tag'
        run: echo newTag=$(cat ./VERSION) >> "$GITHUB_OUTPUT"

    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}

  release:
    needs: [bump-version]
    name: 'Release'
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: my app
          tag_name: ${{ needs.bump-version.outputs.newTag }}
          body: something
          token: ${{ secrets.GITHUB_TOKEN }}
